# Header
menu:
  HOME: /
  PHOTOS: /instagram

# SubNav
subnav:
  github: "https://github.com/myoneray"
  mail: "myoneray@gmail.com"
  weibo: "http://weibo.com/2102785392"
  zhihu: 'https://www.zhihu.com/people/invi-s'
  # rss: /atom.xml
  #douban: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:

# Content
excerpt_link: more
fancybox: true
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.ico

#你的头像url
avatar: /avatar/avatar.jpg

#是否开启分享
share_jia: false
share_addthis: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
# duoshuo: "litten-hexo"

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: 'NOTES'
  tagcloud: 'TAGS'
  friends: 'BOOKMARKS'
  # aboutme: '关于我'

friends:
  uisdc: http://www.uisdc.com/
  transparenttextures: https://www.transparenttextures.com/
  michellechang: http://www.michellechang.com/

permalink: /404.html
aboutme:
